---
- name: Prepare AKS Jumpbox VM
  hosts: all
  become: true

  tasks:
    - name: Get AZ CLI Install Script
      become: true
      ansible.builtin.command: wget https://aka.ms/InstallAzureCLIDeb 
    
    - name: Add executable permissions to AZ CLI Install Script
      become: true
      ansible.builtin.command: chmod +x InstallAzureCLIDeb

    - name: Install AZ CLI
      become: true
      ansible.builtin.command: ./InstallAzureCLIDeb
      
    - name: Install AZ AKS CLI
      become: true
      ansible.builtin.command: az aks install-cli

      