---
- name: Install Nginx on Webservers
  hosts: webservers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      become: true

