---
- name: Install Nginx on Webservers
  hosts: all
  become: true

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 60
        timeout: 320
        
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: true

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      become: true

